\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={R Learning Guide},
            pdfauthor={Mike Bader},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\ImportTok}[1]{{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{{#1}}}}
\newcommand{\BuiltInTok}[1]{{#1}}
\newcommand{\ExtensionTok}[1]{{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{{#1}}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{R Learning Guide}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{Mike Bader}
  \preauthor{\centering\large\emph}
  \postauthor{\par}
  \predate{\centering\large\emph}
  \postdate{\par}
  \date{February 2018}


\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\section{Welcome to R!}\label{welcome-to-r}

You are embarking on an exciting adventure to learn extremely powerful
software that you can download \textbf{for free}.

\subsection{What is R?}\label{what-is-r}

Let's start by describing this powerful tool to start. R is both:

\begin{itemize}
\item
  A statistical computing software
\item
  A full-fledged programming language
\end{itemize}

If you have learned other statistical software, you might wonder why you
would want to learn another. Especially because many find that R has a
steeper learning curve than these software programs.

\subsection{Difference from Other Statistical
Software}\label{difference-from-other-statistical-software}

Other statistical software like Stata, SPSS, and SAS do one thing: they
take a table (spreadsheet) of data and statistical commands to analyze
that data.

R can do this, too. But R can do many more things because R is an entire
programming language. It has many different types of data that you can
use. You can put in a table (called a ``data frame'' in R-speak), but
you have lots of other types of data that you can use. It offers much
more flexibility than other statistical software.

BUT, that flexibility comes at the cost of simplicity.

\subsection{Why R?}\label{why-r}

So why make you learn something that's harder than what you have already
learned?

\begin{itemize}
\item
  R is open source (free as in speech), which means that many different
  people can help extend the language to do common tasks or specialized
  analysis
\item
  R is the future of statistical software; employers will be
  increasingly moving to R
\item
  Lest we forget, let us remember that R is \textbf{free} (as in beer);
  you can use it on any computer and with any employer. Many of you will
  be working for employers that might not have large budgets; learning
  free software means that you will always be able to use it.

  \begin{longtable}[]{@{}lrl@{}}
  \toprule
  SAS\footnote{For SAS Analytics Pro
    \url{https://www.sas.com/en_us/software/analytics-pro.html}; January
    20, 2018} & \$9,720.00 & + Windows only\tabularnewline
  SPSS\footnote{\url{https://www.ibm.com/products/spss-statistics/pricing};
    January 20, 2018} & \$99.00/month & + \$237.00/month
  add-ons\tabularnewline
  Stata\footnote{Stata 15 government \& nonprofit pricing
    \url{https://www.stata.com/order/new/gov/single-user-licenses/dl/};
    January 20, 2018} & \$1,695.00 & + \$300 for large
  datasets\tabularnewline
  R & \$0.00 &\tabularnewline
  \bottomrule
  \end{longtable}
\end{itemize}

We're talking about a substantial amount of money!

\subsection{Getting R}\label{getting-r}

\subsubsection{Download R}\label{download-r}

I hope that I have convinced you to at least try R at this point. That
means you will need to get this amazing, powerful, and cost-effective
software. You will need to download R. To do so Go to
\url{https://www.r-project.org/} and look for the link that says
``Download.'' After you do that, you will be sent to a list of mirrors
(servers that distribute R so that no single server gets overloaded).
Find the United States and download one from that lists (I use the
\href{https://mirrors.nics.utk.edu/cran/}{National Institute for
Computational Sciences in Oak Ridge, TN}).

\subsubsection{RStudio}\label{rstudio}

If you open up R after downloading it, you will see that it gives you
\emph{nothing} except a command line to type in commands to be run. This
is not ideal and would make R \emph{really} difficult if that was the
only way with which you could interact with R.

That is where RStudio comes in. RStudio is an \emph{Integrated
Development Environment (IDE)} for R. That means that RStudio gives you
a window into R--basically it acts as a gopher between you and R.

In acting as a gopher, it provides a nice \emph{graphical user interface
(GUI)} that makes R a lot easier to use.

There are four different windows in RStudio that you will use:

\begin{description}
\item[Source (ctrl-1)]
This is where you keep your scripts where you do your analysis. These
are the same as {\texttt{.do}} files in Stata.
\item[Console (ctrl-2)]
This is where you can type commands directly to tell R what to do. You
should use this sparingly because only entering commands in the console
makes it difficult to reproduce what you have done. My advice: work in
the source window, then copy/paste into the console (or source the
command directly by pressing `ctrl-Enter'---we'll get to that)
\item[Environment]
This window shows you all of the objects that are currently available in
R. Remember how I told you that R can hold different types of data? This
is where you will find all of them. A second tab in that window contains
your history, which contains the list of commands that you have entered
into the console.
\item[Viewer]
This window is where you will view help files and plots that you make
(you can view a whole bunch of other stuff down there, but those are for
more advanced applications).
\end{description}

To get RStudio, you will go to \url{https://www.rstudio.com/} and then
find the link for RStudio and download. This software is also free.

\subsubsection{Getting Help}\label{getting-help}

As you go on this adventure, you will likely need help along the way.
There are a couple of great resources on the web to help you learn just
about everything that you would like to do.

\begin{description}
\item[\href{https://stackoverflow.com/questions/tagged/r}{Stack
Overflow}]
provides user-generated answers to questions posed in forums. Good
answers tend to filter to the top of the list based on an ingenuous
ranking system of votes and points.
\item[\href{https://rseek.org/}{Rseek}]
gives Google-like search functionality to find R-related material.
\item[\href{https://www.r-bloggers.com/}{R-bloggers}]
is a blog with posts that cover tutorials and code for basic to advanced
material
\end{description}

\section{Variables and Data}\label{variables-and-data}

\subsection{What is a Variable?}\label{what-is-a-variable}

In R, \emph{variables} differ from variables in other statistics
programs. In Stata or SPSS, variables represent columns in a dataset. In
R, variables can take on many different forms: vectors (a row of numbers
or letters), datasets (called ``dataframes''), scalars (a single number
or letter), among many others
(\href{https://www.statmethods.net/input/datatypes.html}{here} is a list
of different R objects).

\hypertarget{vars_numeric}{\subsubsection{Numeric}\label{vars_numeric}}

We will ``assign'' variables in R using the operator
\texttt{\textless{}-}. If we want to create a variable containing the
number of states in the United States (50) to a variable named
\texttt{N\_states} for {[}N{]}umber of {[}states{]}\footnote{R reads
  periods \texttt{.} as spaces, like underscores. Those who code in
  Python will likely find this convention frustrating since Python uses
  the dot notation to identify methods or properties of an object's
  instance. In my own coding, I now try to use underscores rather than
  dots so that I do not continue to confuse myself, even though dots are
  conventional in R.} we might write:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{N_states <-}\StringTok{ }\DecValTok{50}
\end{Highlighting}
\end{Shaded}

Any time we write \texttt{N\_states}, R will read that as ``50''. So if
I type \texttt{N\_states\ *\ 2} into the console, I will get:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{N_states *}\StringTok{ }\DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 100
\end{verbatim}

\hypertarget{vars_string}{\subsubsection{Strings}\label{vars_string}}

We can also assign strings, or in R-speak ``characters'', to variables.
I can create a variable called \texttt{my\_state} that contains the
string \texttt{Maryland} in it. We can then do things with that variable
like make parts of sentences.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my_state <-}\StringTok{ "Maryland"}
\KeywordTok{paste}\NormalTok{(}\StringTok{"I live in"}\NormalTok{,my_state)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "I live in Maryland"
\end{verbatim}

Here we have used the \texttt{paste()} \emph{function} to glue the
string \texttt{"I\ live\ in"} to the string stored in
\texttt{my\_state}, which R reads as \texttt{"Maryland"}. If you wanted
to change the value in your state, you would only need to change the
value of \texttt{my\_state}, enclosed in quotes, to represent your
state. As a matter of fact, you don't even need to enter a state into
the variable \texttt{my\_state}, you can enter any value you want. For
example:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my_state <-}\StringTok{ "a galaxy far, far away"}
\KeywordTok{paste}\NormalTok{(}\StringTok{"I live in"}\NormalTok{,my_state)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "I live in a galaxy far, far away"
\end{verbatim}

This works because R doesn't care what string \texttt{my\_state}
actually contains. Now that I have entered
\texttt{"a\ galaxy\ far,\ far\ away"}, R will just look for the name
\texttt{my\_state} and substitute the value stored in that variable. You
should note that \emph{variable names are for humans} to make sense of
what's contained within them. R does not care what you name a variable,
it just cares what you assign to the variable of that name.

\textbf{Watch out:} One common error is to forget to enclose words in
quotes that you want to use as strings. R will ``throw'' an error if you
type the following:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my_state <-}\StringTok{ }\NormalTok{Maryland}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Error in eval(expr, envir, enclos): object 'Maryland' not found
\end{verbatim}

You will see that the console tells you ``Error: object `Maryland' not
found''. That means that R looked for a variable (that's the object its
referring to) called \texttt{Maryland}, but it couldn't find one. In
order for the string of letter M-a-r-y-l-a-n-d to be read as the string
``Maryland'', you need to enclose it in quotes.

\hypertarget{vars_vector}{\subsubsection{Vectors}\label{vars_vector}}

Vectors are another useful type of object in R. We create these by
``combining'' elements, separated by commas, into a single object. One
of the most annoying aspects of R is that you must use a function,
\texttt{combine()} to create vectors. Fortunately, because we use that
function so often, it has an abbreviation: \texttt{c()}.\footnote{For
  those unfamiliar with other programming languages, this might not seem
  weird. For those of us who program in other languages, for example
  Python, we get used to typing \texttt{my\_list\ =\ {[}1,2,3,4{]}}.
  Creating a similar object in R requires that we type
  \texttt{my\_list\ =\ c(1,2,3,4)}. I usually introduce errors in my
  code when I switch back to R from another language because I try to
  type \texttt{my\_list\ =\ (1,2,3,4)} and end up with an error.} Let's
say that I want to create a vector containing the states in which I have
lived. I would write:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my_states <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Colorado"}\NormalTok{,}\StringTok{"Washington"}\NormalTok{,}\StringTok{"Maryland"}\NormalTok{,}\StringTok{"Texas"}\NormalTok{,}
               \StringTok{"Michigan"}\NormalTok{,}\StringTok{"New York"}\NormalTok{,}\StringTok{"Pennsylvania"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Anytime I type \texttt{my\_states}, it will return the vector containing
this set of string values. With a ``for loop'' we could do the following
(don't worry about following the for-loop, just see that I can operate
on each element of the vector):

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{for(state in my_states) \{}
    \KeywordTok{print}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"I lived in"}\NormalTok{,state))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "I lived in Colorado"
## [1] "I lived in Washington"
## [1] "I lived in Maryland"
## [1] "I lived in Texas"
## [1] "I lived in Michigan"
## [1] "I lived in New York"
## [1] "I lived in Pennsylvania"
\end{verbatim}

Note that when I initialized the variable \texttt{my\_states}, I split
the code across two lines. Normally R would execute each line as a
command. R, however, allows you to split lines inside of parentheses and
it won't attempt to execute the command until it finds the closing
parens. This allows you to keep your code in a reasonable width, which
improves legibility (generally try to keep each line under 80 characters
in width).

\subsection{Open a Dataset}\label{open-a-dataset}

None of this provides much excitement. After all, if you are reading
this tutorial, you likely want to analyze data. In order to analyze
data, we need to open a dataset to analyze.

\textbf{Data frames.} Remember that R stores every object with a
variable name: this includes datasets! As I mentioned above, R names
datasets ``data frames''. That means that we will load the data into a
variable and then operate on that variable to do things with the data.
This differs substantially from Stata or SPSS where you will load a
single data set and then the software will assume that you are refering
to that dataset when you send commands to the program.

For this example, we will use data from the 2016 DC Area Survey
(DCAS2016), a survey of residents in multiracial neighborhoods in
Washington, DC and the surrounding jurisdictions. The data are available
at
\url{https://hg.mikebader.net/private/dcas2016/raw-file/tip/Dataset/DCAS_2016_weighted.csv}
(email me to get the username and password if you would like to download
the data).

The file contains the data in \emph{comma separated values (csv)}
format. The first row contains ``variable'' (in the sense of data
variables, not in the R sense) names separated by commas. Each of the
following rows contains the responses for a single respondent with each
reponse separated by a comma.

Comma separated values can always be read, which gives them a huge
advantage over files saved in a format that cannot be read. It's like
saving a text file on your computer versus a Microsoft Word document. It
seems fine because of Word's ubiquity. But I'm old enough to remember
when WordPerfect was the word processor that everyone used. Good luck
getting one of those files to open now.

I digress. We have two options for data that are available on the web:
we can download the data and open the file from our machine or we can
open the data directly from the internet. My advice would be this: if
you a dataset will not change, then download a copy so that you can use
it at any time. If a dataset will change, for example by getting new
data appended as they become available, it's probably better to open the
data from the internet.

\hypertarget{data_local}{\subsubsection{Loading data from a file on your
computer}\label{data_local}}

You will open data that you have saved on your own machine (also known
as loading from a `local file'). To be able to open the data, you will
have to tell R where you have stored it on your computer. To do this,
you will need to know a) the directory in which you stored it and b) the
file name. Every operating system stores files into different
directories. You probably know these as folders when you go to ``My
Computer'' on a PC or ``Macintosh HD'' on a Mac (if you use Linux, I
will assume that you know all of this and you can probably tell me how
I've gotten this wrong). The folders just provide a visual
representation of directories.

To open the data, you will use the function \texttt{read.csv()}. The
function takes one required \emph{argument}, the file name to be read. R
will then convert the text in the .csv file into a dataframe that we can
manipulate and analyze. Remember, though, that \emph{we need to assign
the dataset to a variable in R!} I downloaded my data into a drive
called ``\textasciitilde{}/work/Data/DCAS/dcas2016/sourceData/'' and I
kept the original file name, ``DCAS\_2016\_weighted.csv'', and want to
store the data in an object called \texttt{dcas}. So, I would write:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dcas <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"~/work/Data/DCAS/dcas2016/Dataset/DCAS_2016_weighted.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Let's break what we did here into its parts:

\begin{itemize}
\item
  {\texttt{dcas}}\\
  This is the object that holds the dataset that we read from the file.
  If we ever want to refer to the dataset, we would need to reference
  its name, {\texttt{dcas}}, first. One of the really cool things about
  R is that you can have multiple datasets open at the same time; that
  means, however, that you have to refer to the dataset that you want to
  use by its name.
\item
  {\texttt{\textless{}-}}\\
  Just as with the variables above, this means ``assign'' the contents
  of the file to the variable name \texttt{dcas}.
\item
  {\texttt{read.csv()}}\\
  This is the \emph{function}. You can tell that it is a function
  because it has parentheses after it. Inside the parentheses are
  different \emph{arguments} that you pass to the function. A function
  will then take those options and do something with them.
\item
  {\texttt{"\textasciitilde{}/work/Data/DCAS/dcas2016/Dataset/DCAS\_2016\_weighted.csv"}}\\
  is a file that holds the data that we want. Notice that we must put
  the file name in quotations. Otherwise R would look for an object of
  the name
  \texttt{\textasciitilde{}/work/Data/DCAS/dcas2016/Dataset/DCAS\_2016\_weighted.csv}
  (which would fail miserably).
\end{itemize}

R did not complain to us, so that's a good sign. But, the data might not
have loaded correctly, so I always like to check. You can do this in two
ways if you are using RStudio. The first, and my preferred way, to check
the data is to use the \texttt{View()} function, which will show you the
contents of the object in the source window.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{View}\NormalTok{(dcas)}
\end{Highlighting}
\end{Shaded}

You can see the result of the \texttt{View(dcas)} command in the source
pane (top left pane) in the image below. The data appear to be set up
correctly. The data's variables are listed across the top, the actual
values in the cells. Everything looks good!

\includegraphics[width=5in]{ch1_variables_and_data/images/View_function_screenshot}

The \texttt{head()} function provides another way to check the data.
This works whether or not you are using RStudio. The \texttt{head()}
function takes one required argument, the data frame object. By default
it will show you the first six rows of data. You can add an extra
argument, however, to tell it how many rows you want reported.

Although most R tutorials and resources tell you to use \texttt{head()},
I don't find it useful because it prints so much data, it can be very
difficult to read. Below, I will show you what the data look like
including only the first 15 columns of the data. If you would like to
see the full results in all of their ugliness, you can type
\texttt{head(dcas)} rather than what I have here. Just remember, I
warned you!

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(dcas[,}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{:}\DecValTok{15}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   X study studycase weight   q1 q2 q3 q4                  q5
## 1 1 O1087     10001 0.3054  Own  0  2 13      Very satisfied
## 2 2 O1087     10002 3.8336 Rent  4  3 16      Very satisfied
## 3 3 O1087     10003 1.1124  Own  1  2 16      Very satisfied
## 4 4 O1087     10004 0.5104  Own  1  1  8      Very satisfied
## 5 5 O1087     10005 0.2154  Own  0  0 12 Extremely satisfied
## 6 6 O1087     10006 0.2229  Own  0  1 12      Very satisfied
##                            q6              q7              q8
## 1 A much better place to live   1 to 4 blocks   Very unlikely
## 2 A much better place to live   5 to 9 blocks   Very unlikely
## 3 A much better place to live 10 to 25 blocks   Very unlikely
## 4 A much better place to live   5 to 9 blocks Somewhat likely
## 5 A much better place to live   5 to 9 blocks     Very likely
## 6 A much better place to live   1 to 4 blocks   Very unlikely
##                                       q9 q10_1 q10_2
## 1     Become a much better place to live  Some A few
## 2  Become a somewhat worse place to live A few  None
## 3                  Stayed about the same  None  None
## 4                  Stayed about the same  Most  None
## 5     Become a much better place to live A few A few
## 6 Become a somewhat better place to live  None  None
\end{verbatim}

\hypertarget{data_internet}{\subsubsection{Loading Data from the
Internet}\label{data_internet}}

The other option you have to read data into R is to read it directly
from the internet. In this case, you will pass the URL where the data
are stored to the \texttt{read.csv()} file rather than a file in a local
directory. As I mentioned above, this feature might be especially good
for data that are updated regularly.

Zillow provides one such source of data. On their
\href{https://www.zillow.com/research/data/}{research data page}, Zillow
provides a number of time series datasets that they update either every
quarter or every month. One could use these updated data to track trends
and automatically get the most recent results available by downloading
from the web.

The data that I will use for this example uses Zillow's proprietary
\href{https://wp.zillowstatic.com/3/ZHVI-InfoSheet-04ed2b.pdf}{Home
Value Index (ZHVI)} because it contains estimates over many years for
most US metropolitan areas. The file is located at:
\url{http://files.zillowstatic.com/research/public/Metro/Metro_Zhvi_AllHomes.csv}.

Therefore, we will download the data by passing that URL to the
\texttt{read.csv()} function rather than a file on our own computer
(remember the put the URL in quotes).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{zillow <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"http://files.zillowstatic.com/research/public/Metro/Metro_Zhvi_AllHomes.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Now it would be wise to inspect the data, either by using
\texttt{View(zillow)} in RStudio or \texttt{head(zillow)}.\footnote{If
  you inspect it closely, you will see that the first row contains data
  for the entire US rather than an individual metropolitan area. If you
  wanted to use these data to compare metropolitan areas, then you would
  want to remove that row before any analysis. We will discuss how to do
  that later in this Guide.}

\subsection{Review: Variables and Data}\label{review-variables-and-data}

\begin{itemize}
\tightlist
\item
  R provides a versatile, powerful set of tools for free (as in beer)
  with a large and stable user base that can contribute to the
  development (free as in speech)
\item
  R can (and does) store all types of objects into variables, including
  \protect\hyperlink{vars_numeric}{numeric},
  \protect\hyperlink{vars_string}{strings}, and
  \protect\hyperlink{vars_vector}{vectors}
\item
  You must load data into an object and can do so by either downloading
  data and loading it \protect\hyperlink{data_local}{from your local
  machine} or from the \protect\hyperlink{data_internet}{internet}.
\end{itemize}

\section{Descriptive Statistics in R}\label{descriptive-statistics-in-r}

\subsection{What are Descriptive
Statistics?}\label{what-are-descriptive-statistics}

They are \emph{univariate} statistics that describe the characteristics
of respondents in the study. Now remember, descriptive statistics are a
\emph{model}: they abstract all of our data into a single number.

We are going to find the mean and the standard deviation of data from
the DCAS2016

\subsection{Calculating Descriptive Statistics in
R}\label{calculating-descriptive-statistics-in-r}

You should have, from last time, the DCAS2016 data already loaded. I am
going to assume that you have that loaded into a variable called
\texttt{dcas}.

Now, remember that the variable \texttt{dcas} contains a spreadsheet, or
a matrix. R will be looking for you to define the elements of the
spreadsheet based on \emph{rows} and \emph{columns}.

\emph{Columns} In a dataframe, we can refer to a column of data by using
the \texttt{\$} operator. If we write

\begin{verbatim}
dcas$q4
\end{verbatim}

that means, give me all of the rows of the spreadsheet {\texttt{dcas}},
but only the values in column {\texttt{q4}}. What you will get will be a
\emph{vector}. A vector is a series of values (think of a list, but
lists actually have a different meaning in R.)

Now, it turns out that \texttt{q4} corresponds to Question 4 from the
DCAS2016 (logical, right?), which reads:

\begin{quote}
\textbf{4. How many years have you lived in your current neighborhood?}
\emph{Answer 0 if less than 1 year.}\\
\_\_\_\_\_\_\_\_\_\_ \emph{years (write in number of years)}
\end{quote}

If we have done everything right, and we type the following into our
console in RStudio, we should get a list of integers corresponding to
the number of years respondents have lived in their current
neighborhood:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dcas$q4}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    [1] 13 16 16  8 12 12 24 35 12 12 11 19  5  8 11  3 10  1 50  2 22  7 35
##   [24] 38 16 31 29 26 33  3 52 26  1  2 60 50 22 14 20 11 13 10 13 25  3  4
##   [47] 32 20 17  3 20  1 37 27 34 17  2 15 15  7 26  3 22 40  2 10  4 26 17
##   [70] 11 14 41 53 97  5 26 19  3  5 97 60 32  3  3 14 27 37 49  2 30 31 29
##   [93] 18  2 11  3  3 38  4 15  7 20  4 20 56 10 20 10  0 36  1 33  1 10  7
##  [116] 13 15  2 24  9 12 28 11 14  8  2 30  2 11  4  4  0 45 17 40 14 43 13
##  [139]  0  3  5 32 35  7 41 12 20  3 27  8 45 23  3  6  0 26 25 29 25  2 18
##  [162] 18 12 18 32  1 22  7 34 16 50 12 17  2 13 25 14 36 26  5 12  2  3  3
##  [185]  0  3  6  2 17 49 22 20  4  3 23 10  8 10  7 20 50  8 26 20 15  0  8
##  [208] 50 20 12 40  4 35 10 13 22 32  4  0  0  7  2  2  4 18  0 24  8 17 28
##  [231]  8  3 20 15  4  3 14 15  2 28  3 22 50  1 14  2  2  2 40 14 18 97  2
##  [254] 15 30  3 15  9  3 18 26 23 20 14  2  0 30  1 18  6  6 11 25 20  9 10
##  [277] 27 11 40 97 13  0 20  2  5 66 27 12 25  6  3  3 12 24  6 20  2 18 28
##  [300]  0 45 20  3 27  1  0 52 31 30 42  8 35  2 35  2 12 12 15 11  1 32 46
##  [323]  3  6 10  2 32 31  1 17  6  3 15  3  8 19 20 11 15 13  9 14  4 25 51
##  [346] 10 26 35 14  8  2 22 18 28  5 15 22  2 19 15  0  2 25 32  0 13 15 28
##  [369] 30 15  4  6 16 47  7  0 15 12 23  8  5 13 11 10 25  0 27  8  5 15 41
##  [392]  3 18 20  4  8 64 10 12 49 12  0  7 30 21 16 17 10  7 34  1 18  3  3
##  [415]  5 23 22 23 16 18 32 25 33  3 50 20  2  3  3 29 20  0  2 20  4  0  5
##  [438] 11  3  6  8  1 20 10  0  4 20 31 23  6 25 15 15 13 27  4  6  0 25  4
##  [461] 53 28  3 19 16 18  7  8  9 35 35 30  8  2  1  2  1 32 41  5 37  7  6
##  [484] 28  7 30 30 25 40 97 10  1  8 25  5 12  2  2 22 22 36  5  2 31 13 16
##  [507] 35 31  5  8 11  0  5 29 25 25 12 58 25 24  4 10 15  3 15  5  2  8 24
##  [530] 19  4 16  5 12  1  8 50 13 17  2 26 20  1  0 21 19  5 32  3 41 19 16
##  [553]  2 21  0  5 10 12 97 20  3 23 24  7  4  2  5  0  7  5 16  5 13  0  7
##  [576]  4 26 13  6 33 22  1  3 16 25 15 15  2  7 34 31  6  7  2 20 10 13 10
##  [599]  3 20 24 23  6  4  6 28  8  2 12 16 23 34 15 11  2 17 58  7 17  6  5
##  [622]  3 10 22 20 21 16 34  8 11  3 26  1  6 20 19 26 30 24 15 33  5  5 15
##  [645] 15 31  2 30 38 38  5 10  7  3 11 17 15 13 10  2 36 16  7  3 11 15 97
##  [668] 43  5 31 45  7  2 30 25  0 12 14 20  7 24 30 33  1 30 13 10 17 33 31
##  [691]  1  2  8  7 18  1  4 40  9 31 24 10 20  6 59 11  6  5 97  8  0  5  6
##  [714]  2 10 34  9 13  2 17  3  4  0  2  2 16 29  8 29  7 10  5 31  2 10  2
##  [737] 27 97 16  0  5 15  6  0 97 10 22  8 20 44 28 32 15 27  5  4  2 11  5
##  [760]  8  6 10 15  5  8  9 12  3 10 30  6  6  0  3 18 10 30 97  0  5 10 10
##  [783] 30  8  0 12  1  0  0 18  3  3 16 20  7 18 32 25  5  9  5  8  8 17  3
##  [806] 14 22 20 19 19  4  2 16 10  3  3 26  2  4  0  7  1 25 17  1  4 31  2
##  [829] 30 25  1  2 22 52 15  2 50 29  1 97  1 14  4 16  1 20  9 14 32 33 14
##  [852] 30  5 15 15  6  0 25 60 12  5 14 97 10 20 12  9  5  2 20 20  4 14  3
##  [875] 42  5  5  0 27 10 33 23 15  1 20  4  2  3 36  2  8 11  2 30 15  2  3
##  [898] 15  3 15 20  1  2 12  3  5  5  2  6 20 13  6  0  5 10 10 10 17 15 38
##  [921] 17 12 44 11 17 12  0 10  3 23 13 33 13 22  2 20  7  7  3  5 12  8 15
##  [944] 97  3 97  0 16 22 15 45 15 30 37 43  2  2 14  3  6 21 15 30 12  9 10
##  [967] 30  9 17  7 17  7 21  4  7  2 13 97 16 17  9  1 30 26 18  4 38 11 14
##  [990] 12 20  3  6 15 18 38 10  3 75  1
##  [ reached getOption("max.print") -- omitted 222 entries ]
\end{verbatim}

A couple of notes:

\begin{itemize}
\item
  What was in the .R file that I ran is contained in the gray box.
\item
  The numbers without brackets are the elements, the actual responses,
  for each of the 1,222 respondents; the first respondent has lived in
  their neighborhood for 13 years, the second for 16, the third also for
  16, and so on.
\item
  The numbers in brackets (e.g., {\texttt{{[}1{]}\ {[}15{]}\ {[}29{]}}})
  represent which element number the line of output starts with; so the
  first element in line 1 is\(\ldots\)well\(\ldots\)one. The first
  element of the second line of output starts with element number 15
  (and if you look at the number of elements in the first row, you will
  see that there are 14 elements).
\end{itemize}

Now that does not seem like a way to report anything -- even R is like,
um\(\ldots\) this is too long for me. A better number would be the
\emph{mean}. We want to know the average number of years residents have
lived in their neighborhood.

To get that, we would put the following in our code:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(dcas$q4)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15.95499
\end{verbatim}

\begin{itemize}
\item
  {\texttt{mean()}} is a function that says give me the mean of all of
  the numbers inside my parentheses, in this case the vector
  {\texttt{dcas\$q4}}.
\item
  The response starts with {\texttt{{[}1{]}}}, which tells us that the
  first element of the responses on that line starts with the first
  element. It's not particularly helpful in this case because there is
  only one element, which is\(\ldots\)
\item
  {\texttt{15.95499}}, the average number of years that respondents
  lived in their neighborhoods
\end{itemize}

Now, unlike Stata or SPSS, R makes it very easy to save that value into
another value that we can then use. We just need to assign it to a
variable name, like so:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mean_years <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(dcas$q4)}
\end{Highlighting}
\end{Shaded}

Uh oh! We didn't get any output!!!

That's okay, we actually shouldn't get any output. Rather than telling
\emph{us} what the value is, R gives that value to the variable
\texttt{mean\_years}. But, if we type \texttt{mean\_years} into our
file, then we get:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mean_years}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15.95499
\end{verbatim}

Okay, so we have the average number of years respondents have lived in
their neighborhood stored in the variable \texttt{mean\_years}. But, we
probably don't want to report the value to five decimal places; after
all, we were only precise to the number of years. It probably makes
sense to round the value to one decimal place. To do that, we would use
the function \texttt{round()}:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{round}\NormalTok{(mean_years,}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16
\end{verbatim}

When we do, it turns out that it equals 16 which is actually 16.0, but
if the last digit equals zero, R does not report it.

We could do this all in one step if we wanted. Remember that
\texttt{mean\_years} equals the value of \texttt{mean(dcas\$q4)}, so
figuring out the rounded value would be: \texttt{round(mean(dcas\$q4))}:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{round}\NormalTok{(}\KeywordTok{mean}\NormalTok{(dcas$q4),}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16
\end{verbatim}

And we could save that final value into the variable
\texttt{mean\_years}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mean_years <-}\StringTok{ }\KeywordTok{round}\NormalTok{(}\KeywordTok{mean}\NormalTok{(dcas$q4),}\DecValTok{1}\NormalTok{)}
\NormalTok{mean_years}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16
\end{verbatim}

Now let's find the standard deviation. The function for standard
deviation in R is \texttt{sd()}. To get the value to one decimal place
we would write:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sd_years <-}\StringTok{ }\KeywordTok{round}\NormalTok{(}\KeywordTok{sd}\NormalTok{(dcas$q4),}\DecValTok{1}\NormalTok{)}
\NormalTok{sd_years}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16.1
\end{verbatim}

We have a mean of 16 and a standard deviation of 16. Seems to me that
the variable can't be normally distributed. Let's look at a histogram to
see:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(dcas$q4)}
\end{Highlighting}
\end{Shaded}

\includegraphics{RLearningGuide_files/figure-latex/hist-1.pdf}

Sure enough, it's not. But we'll worry about that later.

\subsection{Calculating Descriptive Statistics of Categorical
Variables}\label{calculating-descriptive-statistics-of-categorical-variables}

This process works well for continuous variables, but for categorical
variables we want to report the percentage or proportion of the
respondents who fall in each category. To do that, we will use the
\texttt{table()} command (which is like \texttt{tab} in Stata).

Let's look at Question 1 from the DCAS2016:

\begin{quote}
\textbf{1. Do you rent your home, own it, or do you have some other
arrangement?}

\_\_\_\_ Rent

\_\_\_\_ Own

\_\_\_\_ Some other arrangement
\end{quote}

If we tried to calculate the mean of Question 1, let's see what we would
get:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(dcas$q1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in mean.default(dcas$q1): argument is not numeric or logical:
## returning NA
\end{verbatim}

\begin{verbatim}
## [1] NA
\end{verbatim}

As Scooby Doo would say, Ruh Roh!!! Let's parse what R returned here. On
the first line, R complained:

\begin{verbatim}
Warning in mean.default(dcas$q1): argument is not numeric or logical:
\end{verbatim}

In the first part of the statement (before the colon) R is telling us
that it is giving us a warning, which means that the program will not
stop running but something might be wrong. In the second part of the
statement, it is telling us that the data we passed, \texttt{dcas\$q1}
does not contain either numeric data or logical (True/False) data. That
makes sense, this is a categorical variable. We have three response
options: Rent, Own, Some other arrangement. It doesn't make sense to
take the mean of that categorical value.

In the second line, R tells us:

\begin{verbatim}
returning NA
\end{verbatim}

Okay, this is easier. In R, the value \texttt{NA} means that the value
does not exist. Together, in these two lines R is telling us:

\begin{quote}
I'm warning you that you gave me a value that doesn't make sense with
this function (you should have given me either numbers or a list of
Trues and Falses), so I'm going to give you back a placeholder that
represents nothing.
\end{quote}

What we want to do instead is to list the possible options using the
\texttt{table()} function, as I mentioned earlier. Let's see what we get
when we do that:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(dcas$q1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##              No Answer                    Own                   Rent 
##                      9                    859                    318 
## Some other arrangement 
##                     36
\end{verbatim}

This looks better. We find out that 859 respondents own their homes, 318
rent, 36 have some other arrangement, and 9 gave no answer.\footnote{Technically
  these should be represented by \texttt{NA} since they don't have an
  answer, but we will save that for a later date.}

Okay, that's helpful, but not exactly what we want. We want to know the
\emph{proportion} of respondents who gave each value. We calcluate the
proportion giving response \emph{r} as:

\[P(r) = \frac{N_r}{N}\]

The proportion (or probability) that respondent answered Question 1 with
response category \(r\) equals the number of respondents who answered
the question with category \(r\) divided by the number of respondents,
\emph{N}. To make this more concrete:
\[P(own)=\frac{N_{own}}{N}=\frac{859}{(859+318+36+9)}\approx0.70\].

We could go through and do all of those calculations, or we can have R
do it for us. I would prefer to let R do it for me. To do that, we will
need to figure out how many respondents there are. The function
\texttt{nrow()} tells us how many rows there are in a dataframe.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{N <-}\StringTok{ }\KeywordTok{nrow}\NormalTok{(dcas)}
\NormalTok{prop_own <-}\StringTok{ }\KeywordTok{table}\NormalTok{(dcas$q1)/N}
\NormalTok{prop_own}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##              No Answer                    Own                   Rent 
##            0.007364975            0.702945990            0.260229133 
## Some other arrangement 
##            0.029459902
\end{verbatim}

What we just did was to tell R to divide each cell in the table created
by \texttt{table(dcas\$q1)} by the number of respondents, \texttt{N}
(which equals 1222). The table we got was better, but still not great
given the long decimals. Let's round them off and replace what's stored
in \texttt{prop\_own} with the rounded values. Since we have
proportions, it would make sense to round to two or three decimal
places:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prop_own <-}\StringTok{ }\KeywordTok{round}\NormalTok{(prop_own,}\DecValTok{2}\NormalTok{)}
\NormalTok{prop_own}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##              No Answer                    Own                   Rent 
##                   0.01                   0.70                   0.26 
## Some other arrangement 
##                   0.03
\end{verbatim}

Now you could report the descriptive statistics for the categorical
variables as the proportion of respondents who reported being in each
category.


\end{document}
